### ISSUE TITLE
Colors lost when piping

### ISSUE THREAD

**Issue by justinhelmer** [dsawardekar/mocha-fivemat-reporter#4]
In my workflow, mocha is piped in a child process. Unfortunately, colors are lost with this reporter.

I notice you are using `Base.color`, so not exactly sure why.

Other reporters work fine (only tried `dots` and the default reporter).

I pass the `--color` command line option to `Mocha`, which is a known option. I know it works, because other reporters fail to use color unless I pass this option.

I noticed completely replacing the `color` interface with [chalk](https://github.com/chalk/chalk) works as well.

**Comment by justinhelmer** [comment]
I have also posted an issue to `mocha`:

[# 2064: Colors lost when piping](https://github.com/mochajs/mocha/issues/2064)

**Comment by justinhelmer** [comment]
Just a follow-up; issue is resolved with a combination of the pull request that was already submitted to this repo, plus sorting out `supports-colors`. 

FYI, `FORCE_COLORS` will _not_ work in the `2.x` branch of `mocha`.

**Comment by justinhelmer** [comment]
Feel free to close this any time

**Comment by dsawardekar** [comment]
Cool, Thanks for letting me know.
