### ISSUE TITLE
Please bump and publish

### ISSUE THREAD

**Issue by justinhelmer** [dsawardekar/mocha-fivemat-reporter#6]
I still have to use my custom fork until the `package.json` version is bumped and published to `npm`.

Thanks a lot!

**Comment by dsawardekar** [comment]
Merged, thanks!

**Comment by justinhelmer** [comment]
@dsawardekar - greatly appreciated. This is certainly my favorite `mocha` reporter. My hats off to you sir.

**Comment by ELLIOTTCABLE** [comment]
Er, this doesn't appear to be pushed yet? I only see 0.6, which still uses `graceful-fs@2.0.3` via `mocha@1.13.0`:

https://www.npmjs.com/package/mocha-fivemat-reporter
